server:
  port: 8081

spring:
  application:
    name: abcmsc-provider-depart
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    # 自动映射实体类，生成数据库表
    generate-ddl: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///ssm?useUnicode=true&characterEncoding=utf8
    username: root
    password: root123

logging:
  pattern:
    console: level-%level %msg%n
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    com.example.demo: debug

eureka:
  client:
    service-url:
      defaultZone: http://eureka1.com:8000/eureka,http://eureka2.com:8100/eureka,http://eureka3.com:8200/eureka
#  instance:
#    instance-id: 01-abc-msc-provider-8081


info:
  auth: zhengquan
  app.name: learn eureka
  app.desc: just a demo.
  company.name: www.goodluck.com
  company.addr: Beijing China.